- Does it crash with our conftest?
- Try not loading our TrackingStore:
    disable:
        (
            "mlflow.store.tracking.sqlalchemy_store.SqlAlchemyStore",
            "tests/override_tracking_store.py",
        ),
        (
            "mlflow.store.model_registry.sqlalchemy_store.SqlAlchemyStore",
            "tests/override_model_registry_store.py",
        ),

logger = logging.getLogger('sqlalchemy.engine')
if logger:
    logger.setLevel(logging.INFO)
else:
    print("Logger 'sqlalchemy.engine' does not exist.")

- Try installing python with github actions instead of uv (do before start UV)

.venv/bin/pytest --log-cli-level=DEBUG --confcutdir=. -k "not [file" -p no:warnings .mlflow.repo/tests/tracking/test_model_registry.py .mlflow.repo/tests/store/tracking/test_sqlalchemy_store.py .mlflow.repo/tests/store/model_registry/test_sqlalchemy_store.py
          